// Code generated by tool. DO NOT EDIT! 
 package main 

 var MetaData = map[string]interface{}{ 
 "goversion": "go version go1.13.5 darwin/amd64", 
 "commitid": "29273f3af40c2b129ad2699c195c74f1ac9a38a6", 
 "gitbranch": "master", 
 "gitauthor": "gerrit@molen.com", 
 "commitdata": "", 
 "gitmessage": `init`, 
 "builddate": "2020-02-26 15:39:12", 
 "modulename": "molen/haoma/greedy", 
 "projectname": "greedy", 
 "hostname": "MacBook-Pro-101.local", 
 "whoami": "zhangxin", 
 } 

